apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-scheduler-deployment
  labels:
    app: engine-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: engine-scheduler
    spec:
      containers:
      - name: engine-scheduler
        {{- with .Values.engine.scheduler }}
        image: {{ .image }}:{{ .tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
          - name: CACHE_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
          - name: CACHE_READ_REPLICA_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
#          - name: QUEUE_URL
#            valueFrom:
#               secretKeyRef:
#                  name: cluster-secrets
#                  key: queueURL
#          - name: CLUSTER_DB_URI
#            valueFrom:
#               secretKeyRef:
#                  name: cluster-secrets
#                  key: clusterDBURI
          - name: CLUSTER_DB_USER
            value: "admin"
          - name: CLUSTER_DB_PWD
            valueFrom:
               secretKeyRef:
                  name: mongodb-admin-password
                  key: password
#          - name: PASSPHRASE
#            valueFrom:
#               secretKeyRef:
#                  name: cluster-secrets
#                  key: passPhrase
#          - name: MASTER_TOKEN
#            valueFrom:
#               secretKeyRef:
#                  name: cluster-secrets
#                  key: masterToken
#          - name: ACCESS_TOKEN
#            valueFrom:
#               secretKeyRef:
#                  name: cluster-secrets
#                  key: accessToken
        resources:
            requests:
               cpu: {{ .resources.requests.cpu }}
               memory: {{ .resources.requests.memory }}
            limits:
               cpu: {{ .resources.limits.cpu }}
               memory: {{ .resources.limits.memory }}
        {{- end }}
        {{- if .Values.imagePullSecretName }}
        imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
        {{- end }}
