apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioner
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "provisioner-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "provisioner-labels" . | nindent 8 }}
    spec:
      serviceAccountName: provisioner-sa
      containers:
        - name: provisioner
          image: {{ .Values.provisioner.image }}:{{ .Values.provisioner.tag }}
          ports:
          - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretName }}
      {{- end }}
