---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: provisioner-role
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provisioner-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: provisioner-role
subjects:
- kind: ServiceAccount
  name: provisioner-sa
  namespace: default
