apiVersion: v1
kind: Service
metadata:
  name: provisioner
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "provisioner-labels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 3000
