{{- if and .Values.platform.sync.hpa .Values.platform.sync.resources }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: platform-sync-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: platform-sync-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  {{- if hasKey .Values.platform.sync.hpa "targetCpuUtilization" }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.platform.sync.hpa.targetCpuUtilization }}
  {{- end }}
  {{- if hasKey .Values.platform.sync.hpa "targetMemory" }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.platform.sync.hpa.targetMemory }}
  {{- end }}
{{- end }}
