{{- $secret := (lookup "v1" "Secret" .Release.Namespace "minio-credentials") -}}
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  rootUser: agnost-admin
  {{ if $secret -}}
  rootPassword: {{ $secret.data.rootPassword | b64dec }}
  {{ else -}}
  rootPassword: {{ derivePassword 1 "long" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | quote }}
  {{ end -}}
  port: "9000"
  endpoint: {{ .Values.minio.nameOverride }}.{{ .Release.Namespace }}
