apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  rootUser: agnost-admin
  rootPassword: {{ derivePassword 1 "long" .Release.Name .Chart.Name "6bWNQnM3LUWWmHsX" }}
  port: "9000"
  endpoint: {{ .Values.minio.nameOverride }}.{{ .Release.Namespace }}
