apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-password
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ derivePassword 1 "long" .Release.Name .Chart.Name "ZWFr4yGXpmydMJkq" }}
