apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 200m
      memory: 500Mi
  persistence:
    storageClassName: standard
    storage: 3Gi
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                volumeMounts:
                  - mountPath: /opt/rabbitmq/community-plugins
                    name: community-plugins
            volumes:
              - name: community-plugins
                emptyDir: {}
            initContainers:
              - command:
                  - sh
                  - -c
                  - curl -L -v https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez --output /community-plugins/rabbitmq_delayed_message_exchange-3.11.1.ez
                image: curlimages/curl
                imagePullPolicy: IfNotPresent
                name: copy-community-plugins
                resources:
                  limits:
                    cpu: 100m
                    memory: 500Mi
                  requests:
                    cpu: 100m
                    memory: 500Mi
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                  - mountPath: /community-plugins/
                    name: community-plugins
  rabbitmq:
    additionalConfig: |
      default_user_tags.administrator = true
    additionalPlugins:
    - rabbitmq_delayed_message_exchange
    envConfig: |
      RABBITMQ_PLUGINS_DIR=/opt/rabbitmq/plugins:/opt/rabbitmq/community-plugins:/opt/bitnami/rabbitmq/plugins

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: mquser
  namespace: {{ .Release.Namespace }}
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  tags:
    - administrator
  importCredentialsSecret:
    name: rabbitmq-credentials

---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: mquser-permission
  namespace: {{ .Release.Namespace }}
spec:
  vhost: "/"
  userReference:
    name: "mquser"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
