apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: mquser
  password: {{ .Values.auth.rabbitmqPassword }}
  host: rabbitmq.{{ .Release.Namespace }}.svc
