apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: mquser
  password: {{ derivePassword 1 "long" .Release.Name .Chart.Name "c6jC8yXJeZ7qmatp" }}
  host: rabbitmq.{{ .Release.Namespace }}.svc
