{{- $secret := (lookup "v1" "Secret" .Release.Namespace "redis-password") -}}
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ if $secret -}}
  password: {{ $secret.data.password | b64dec }}
  {{ else -}}
  password: {{ derivePassword 1 "long" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | quote }}
  {{ end -}}
