apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ derivePassword 1 "long" .Release.Name .Chart.Name "tz9ADdH2MtBWZQzc" }}
