{{- $secret := (lookup "v1" "Secret" .Release.Namespace "cluster-secrets") -}}
{{- if or .Release.IsInstall not $secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  clusterId: {{ (printf "cls_%s" (uuidv4 | replace "-" "" | trunc 10)) | quote }}
  clusterAcessToken: {{ (printf "at_%s" (uuidv4 | replace "-" "" )) | quote }}
  masterToken: {{ (printf "mt-%s" (uuidv4 | replace "-" "" )) | quote }}
  accessToken: {{ (printf "at-%s" (uuidv4 | replace "-" "" )) | quote }}
  passPhrase: {{ uuidv4 | quote }}
  uiBaseURL: "http://192.168.49.2"
  clusterDBURI: "mongodb://mongodb-svc.{{ .Release.Namespace }}.svc/agnost_enterprise?retryWrites=true&w=majority"
{{- end -}}
