apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: cluster-storage-pvc
   labels:
      app: platform-core
spec:
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 5Gi
