{{- $secret := (lookup "v1" "Secret" .Release.Namespace "cluster-secrets") -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: {{ .Release.Namespace }}
{{- if $secret }}
data:
  clusterId: {{ $secret.data.clusterId | quote }}
  clusterAcessToken: {{ $secret.data.clusterAcessToken | quote }}
  masterToken: {{ $secret.data.masterToken | quote }}
  accessToken: {{ $secret.data.accessToken | quote }}
  passPhrase: {{ $secret.data.passPhrase | quote }}
  uiBaseURL: {{ $secret.data.uiBaseURL | quote }}
  clusterDBURI: {{ $secret.data.clusterDBURI | quote }}
{{- else }}
stringData:
  clusterId: {{ (printf "cls-%s" (uuidv4 | replace "-" "" | trunc 10)) }}
  clusterAcessToken: {{ (printf "at-%s" (uuidv4 | replace "-" ""  )) }}
  masterToken: {{ (printf "mt-%s" (uuidv4 | replace "-" "" )) }}
  accessToken: {{ (printf "at-%s" (uuidv4 | replace "-" "" )) }}
  passPhrase: {{ uuidv4 }}
  {{- if eq .Values.kubernetes-platform "minikube" }}
  uiBaseURL: http://192.168.49.2
  {{- else }}
  uiBaseURL: http://localhost
  {{- end }}
  clusterDBURI: "mongodb://mongodb-svc.{{ .Release.Namespace }}.svc/agnost_enterprise?retryWrites=true&w=majority"
{{- end }}