{{- $secret := (lookup "v1" "Secret" .Release.Namespace "cluster-secrets") -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  {{ if $secret -}}
  clusterId: {{ $secret.data.clusterId | b64dec }}
  clusterAccessToken: {{ $secret.data.clusterAccessToken | b64dec }}
  masterToken: {{ $secret.data.masterToken | b64dec }}
  accessToken: {{ $secret.data.accessToken | b64dec }}
  passPhrase: {{ $secret.data.passPhrase | b64dec }}
  jwtSecret: {{ $secret.data.jwtSecret | b64enc }}
  clusterDBURI: {{ $secret.data.clusterDBURI | b64dec }}
  {{ else -}}
  clusterId: {{ (printf "cls-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name "UzdGjC9FMfm5T6cX" | b64enc | trimSuffix "=" | lower | trunc 10)) }}
  clusterAccessToken: {{ (printf "at-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name "HpwjuTmvj4a6GRXG" | b64enc | trimSuffix "=" | lower)) }}
  masterToken: {{ (printf "mt-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name "Zf7yWn7eNZVqup8Q" | b64enc | trimSuffix "=" | lower)) }}
  accessToken: {{ (printf "at-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name "5fG99EWdTGHWhJmD" | b64enc | trimSuffix "=" | lower)) }}
  passPhrase: {{ derivePassword 1 "maximum" .Release.Name .Chart.Name "zty5mQ6knqtJQJfu" | b64enc | trimSuffix "=" | lower }}
  jwtSecret: {{ derivePassword 1 "maximum" .Release.Name .Chart.Name "e95hJ72NKmpDekuQHvfz" | b64enc | trimSuffix "=" | lower }}
  clusterDBURI: "mongodb://mongodb-svc.{{ .Release.Namespace }}.svc/agnost?retryWrites=true&w=majority"
  {{ end -}}
