{{- $secret := (lookup "v1" "Secret" .Release.Namespace "cluster-secrets") -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  {{ if $secret -}}
  clusterId: {{ $secret.data.clusterId | b64dec }}
  clusterAccessToken: {{ $secret.data.clusterAccessToken | b64dec }}
  masterToken: {{ $secret.data.masterToken | b64dec }}
  accessToken: {{ $secret.data.accessToken | b64dec }}
  passPhrase: {{ $secret.data.passPhrase | b64dec }}
  jwtSecret: {{ $secret.data.jwtSecret | b64dec }}
  clusterDBURI: {{ $secret.data.clusterDBURI | b64dec }}
  {{ else -}}
  clusterId: {{ (printf "cls-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | lower | trunc 10)) }}
  clusterAccessToken: {{ (printf "at-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | lower)) }}
  masterToken: {{ (printf "mt-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | lower)) }}
  accessToken: {{ (printf "at-%s" (derivePassword 1 "maximum" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | lower)) }}
  passPhrase: {{ derivePassword 1 "maximum" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | lower | quote }}
  jwtSecret: {{ derivePassword 1 "maximum" .Release.Name .Chart.Name uuidv4 | b64enc | trimSuffix "=" | lower | quote }}
  clusterDBURI: "mongodb://mongodb-svc.{{ .Release.Namespace }}.svc/agnost?retryWrites=true&w=majority"
  {{ end -}}
