apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  uiBaseURL: "http://localhost"
  clusterDBURI: "mongodb+srv://mongodb-headless.default.svc.cluster.local/agnost_enterprise?retryWrites=true&w=majority"
  queueURL: "amqps://rabbitmq-nodes.default.svc.cluster.local"
{{- include "clusterIds" . | indent 2 }}
{{- include "tokens" . | indent 2 }}
