{{- $secret := (lookup "v1" "Secret" .Release.Namespace "cluster-secrets") -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
{{ if $secret -}}
data:
  clusterId: {{ $secret.data.clusterId | quote }}
  clusterAcessToken: {{ $secret.data.clusterAcessToken | quote }}
  masterToken: {{ $secret.data.masterToken | quote }}
  accessToken: {{ $secret.data.accessToken | quote }}
  passPhrase: {{ $secret.data.passPhrase | quote }}
  uiBaseURL: {{ (printf "%s" "http://192.168.49.2") | b64enc | quote }}
  clusterDBURI: {{ (printf "%s" "mongodb+srv://mongodb-srv.default.svc.cluster.local/agnost_enterprise?retryWrites=true&w=majority") | b64enc | quote }}
  queueURL: {{ (printf "%s" "amqps://rabbitmq-nodes.default.svc.cluster.local") | b64enc | quote }}
{{ else -}}
stringData:
  clusterId: {{ (printf "cls_%s" (uuidv4 | replace "-" "" | trunc 10)) | quote }}
  clusterAcessToken: {{ (printf "at_%s" (uuidv4 | replace "-" "" | quote )) }}
  masterToken: {{ (printf "mt-%s" (uuidv4 | replace "-" "" )) | quote }}
  accessToken: {{ (printf "at-%s" (uuidv4 | replace "-" "" )) | quote }}
  passPhrase: {{ uuidv4 }}
  uiBaseURL: "http://192.168.49.2"
  clusterDBURI: "mongodb+srv://mongodb-srv.default.svc.cluster.local/agnost_enterprise?retryWrites=true&w=majority"
  queueURL: "amqps://rabbitmq-nodes.default.svc.cluster.local"
{{ end -}}