---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: provisioner-role
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provisioner-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: provisioner-role
subjects:
- kind: ServiceAccount
  name: provisioner-sa
  namespace: default
