apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  clusterId: {{ (printf "cls-%s" (randAlphaNum 20)) }}
  clusterAcessToken: {{ (printf "at-%s" (randAlphaNum 20)) }}
  masterToken: {{ (printf "mt-%s" (randAlphaNum 20)) }}
  accessToken: {{ (printf "at-%s" (randAlphaNum 20)) }}
  passPhrase: {{ randAlphaNum 20  }}
  jwtSecret: {{ randAlphaNum 20  }}
  clusterDBURI: "mongodb://mongodb-svc.{{ .Release.Namespace }}.svc/agnost?retryWrites=true&w=majority"
