apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-realtime-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: engine-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-realtime
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: engine-realtime
    spec:
      containers:
      - name: engine-realtime
        image: {{ .Values.engine.realtime.image }}:{{ .Values.engine.realtime.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
          - name: CACHE_HOSTNAME
            value: redis-master
          - name: REALTIME_CACHE_HOSTNAME
            value: redis-master
          - name: CACHE_READ_REPLICA_HOSTNAME
            value: redis-replicas
          - name: CACHE_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
          - name: CACHE_READ_REPLICA_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
          - name: REALTIME_CACHE_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
          - name: MASTER_TOKEN
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: masterToken
          - name: ACCESS_TOKEN
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: accessToken
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 3
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 30
          periodSeconds: 30
{{- if .Values.engine.realtime.resources  }}
        resources:
{{ toYaml .Values.engine.realtime.resources | indent 10 }}
{{- end }}
