{{- if and .Values.engine.realtime.hpa .Values.engine.realtime.resources }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: engine-realtime-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: engine-realtime-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.engine.realtime.hpa.targetCpuUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.engine.realtime.hpa.targetMemory }}
{{- end }}
