apiVersion: v1
kind: Namespace
metadata:
  {{- if eq .Release.Namespace "default" }}
  name: operators
  {{- else }}
  name: {{ .Release.Namespace }}-operators
  {{- end }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
