apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-worker-deployment
  labels:
    app: platform-worker
    namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: platform-worker
    spec:
      initContainers:
      - name: wait-for-redis
        image: redis:alpine
        imagePullPolicy: IfNotPresent
        args: [ 'sh', '-c', 'until redis-cli -h ${CACHE_HOSTNAME} -p 6379 -a ${CACHE_PWD} get hello; do echo "Sleeping a bit..."; sleep 3; done; echo "Redis is ready!";' ]
        env:
          - name: CACHE_HOSTNAME
            value: redis-master
          - name: CACHE_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
      - name: wait-for-rabbitmq
        image: curlimages/curl:8.1.1
        imagePullPolicy: IfNotPresent
        args: [ 'sh', '-c', 'until [ "$(curl -s -u "${USER}:${PASS}" http://rabbitmq.{{ .Release.Namespace }}.svc:15672/api/aliveness-test/%2F)" == "{\"status\":\"ok\"}" ]; do echo "Sleeping a bit..."; sleep 3; done; echo "RabbitMQ is ready!";' ]
        env:
          - name: USER
            valueFrom:
               secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
          - name: PASS
            valueFrom:
               secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
      containers:
      - name: platform-worker
        image: {{ .Values.platform.worker.image }}:{{ .Values.platform.worker.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
          - name: CACHE_HOSTNAME
            value: redis-master
          - name: CACHE_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
          - name: QUEUE_USERNAME
            valueFrom:
               secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
          - name: QUEUE_PASSWORD
            valueFrom:
               secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
          - name: QUEUE_HOST
            valueFrom:
               secretKeyRef:
                  name: rabbitmq-default-user
                  key: host
          - name: MASTER_TOKEN
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: masterToken
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 3
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 30
          periodSeconds: 30
{{- if .Values.platform.worker.resources  }}
        resources:
{{ toYaml .Values.platform.worker.resources | indent 10 }}
{{- end }}
