apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-monitor-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: engine-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-monitor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: engine-monitor
    spec:
      serviceAccountName: provisioner-sa
      initContainers:
      - name: wait-for-redis
        image: redis:alpine
        imagePullPolicy: IfNotPresent
        args: [ 'sh', '-c', 'until redis-cli -h ${CACHE_HOSTNAME} -p 6379 -a ${CACHE_PWD} get hello; do echo "Sleeping a bit..."; sleep 3; done; echo "Redis is ready!";' ]
        env:
          - name: CACHE_HOSTNAME
            value: redis-master
          - name: CACHE_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
      - name: wait-for-mongo
        image: rtsp/mongosh:1.10.1
        imagePullPolicy: IfNotPresent
        args: [ 'sh', '-c', 'until mongosh "${CLUSTER_DB_URI}" --username ${CLUSTER_DB_USER} --password ${CLUSTER_DB_PWD}; do echo "Sleeping a bit..."; sleep 3; done; echo "MongoDB is ready!";' ]
        env:
          - name: CLUSTER_DB_URI
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: clusterDBURI
          - name: CLUSTER_DB_USER
            value: "mongo-user"
          - name: CLUSTER_DB_PWD
            valueFrom:
               secretKeyRef:
                  name: mongodb-admin-password
                  key: password
      containers:
      - name: engine-monitor
        image: {{ .Values.engine.monitor.image }}:{{ .Values.engine.monitor.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
          - name: CACHE_HOSTNAME
            value: redis-master
          - name: CACHE_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
          - name: CLUSTER_DB_URI
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: clusterDBURI
          - name: CLUSTER_DB_USER
            value: "mongo-user"
          - name: CLUSTER_DB_PWD
            valueFrom:
               secretKeyRef:
                  name: mongodb-admin-password
                  key: password
          - name: PASSPHRASE
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: passPhrase
          - name: MASTER_TOKEN
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: masterToken
          - name: ACCESS_TOKEN
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: accessToken
          - name: MINIO_ENDPOINT
            value: {{ .Values.minio.nameOverride }}.{{ .Release.Namespace }}
          - name: MINIO_PORT
            value: "9000"
          - name: MINIO_ACCESS_KEY
            value: appUser
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: userPassword
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 3
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 30
          periodSeconds: 30
{{- if .Values.engine.monitor.resources  }}
        resources:
{{ toYaml .Values.engine.monitor.resources | indent 10 }}
{{- end }}
