apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: platform-sync-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: platform-sync-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.platform.sync.resources.targetCpuUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.platform.sync.resources.targetMemory }}
