apiVersion: v2
name: base
description: Base installation for Cloud Agnost Apps
version: 0.9.13
appVersion: 1.0.0
dependencies:
- name: community-operator
  version: "0.8.0"
  repository: https://mongodb.github.io/helm-charts
- name: rabbitmq-cluster-operator
  version: "3.3.1"
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: "17.10.2"
  repository: https://charts.bitnami.com/bitnami
# postgresql chart needed
#- name: postgres-operator-charts
#  version: "1.10.0"
#  repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
