apiVersion: v2
name: base
description: Cloud Agnost Applications Installation
version: 0.9.132
appVersion: v1.0.39
dependencies:
- name: namespace
  version: "0.0.1"
  repository: "file://../namespace"
- name: ingress-nginx
  version: "4.8.2"
  repository: "file://../ingress-nginx"
  condition: ingress-nginx.enabled
- name: operators
  version: "0.0.2"
  repository: "file://../operators"
- name: redis
  version: "17.10.2"
  repository: https://charts.bitnami.com/bitnami
- name: minio
  version: "5.0.13"
  repository: https://charts.min.io
- name: cert-manager
  version: "v1.13.1"
  repository: https://charts.jetstack.io
