apiVersion: v2
name: base
description: Base installation for Cloud Agnost Apps
version: 0.4.1
appVersion: 0.3.0
dependencies:
- name: community-operator
  version: "0.7.9"
  repository: https://mongodb.github.io/helm-charts
