apiVersion: v2
name: base
description: Base installation for Cloud Agnost Apps
version: 0.2.4
dependencies:
- name: community-operator
  version: "0.7.9"
  repository: https://mongodb.github.io/helm-charts
