apiVersion: v2
name: base
description: Base installation for Cloud Agnost Apps
version: 0.7.2
appVersion: 1.0.0
dependencies:
- name: community-operator
  version: "0.7.9"
  repository: https://mongodb.github.io/helm-charts
- name: rabbitmq-cluster-operator
  version: "3.3.1"
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: "17.10.2"
  repository: https://charts.bitnami.com/bitnami
