# Kubernetes platform. Values can be:
# - minikube (default)
# - dockerdesktop
# - kind
host: minikube

# this is needed to install mongodb-community crd inside the chart via crds/ directory
community-operator:
  community-operator-crds:
    enabled: false

# values for the bitnami redis chart
redis:
  nameOverride: redis
  fullnameOverride: redis
  master:
    persistence:
      size: 2Gi
  replica:
    replicaCount: 1
    persistence:
      size: 2Gi
  auth:
    existingSecret: redis-password
    existingSecretPasswordKey: password
auth:
  redisPassword: tz9ADdH2MtBWZQzc
  mongodbPassword: ZWFr4yGXpmydMJkq
  rabbitmqPassword: c6jC8yXJeZ7qmatp
engine:
  monitor:
    image: "gcr.io/agnost-community/engine/monitor"
    tag: "7d7c39e"
    resources:
      requests:
        cpu: '50m'
        memory: '256Mi'
      limits:
        cpu: '1000m'
        memory: '2Gi'
  realtime:
    image: "gcr.io/agnost-community/engine/realtime"
    tag: "4077190"
    resources:
      targetCpuUtilization: 90
      targetMemory: '250Mi'
      requests:
        cpu: '50m'
        memory: '256Mi'
      limits:
        cpu: '1000m'
        memory: '2Gi'
  scheduler:
    image: "gcr.io/agnost-community/engine/scheduler"
    tag: "4077190"
    resources:
      requests:
        cpu: '50m'
        memory: '256Mi'
      limits:
        cpu: '1000m'
        memory: '2Gi'
  worker:
    image: "gcr.io/agnost-community/engine/worker"
    tag: "7d7c39e"
    resources:
      targetCpuUtilization: 90
      targetMemory: '250Mi'
      requests:
        cpu: '100m'
        memory: '256Mi'
      limits:
        cpu: '1000m'
        memory: '2Gi'
platform:
  core:
    image: "gcr.io/agnost-community/platform/core"
    tag: "7d7c39e"
    resources:
      targetCpuUtilization: 90
      targetMemory: '250Mi'
      requests:
        cpu: '100m'
        memory: '256Mi'
      limits:
        cpu: '1000m'
        memory: '2Gi'
  sync:
    image: "gcr.io/agnost-community/platform/sync"
    tag: "4077190"
    resources:
      targetCpuUtilization: 90
      targetMemory: '250Mi'
      requests:
        cpu: '50m'
        memory: '256Mi'
      limits:
        cpu: '1000m'
        memory: '2Gi'
  worker:
    image: "gcr.io/agnost-community/platform/worker"
    tag: "8804a15"
    resources:
      targetCpuUtilization: 90
      targetMemory: '250Mi'
      requests:
        cpu: '50m'
        memory: '256Mi'
      limits:
        cpu: '1000m'
        memory: '2Gi'
studio:
  image: "gcr.io/agnost-community/studio"
  tag: "9450209"
  resources:
    requests:
      cpu: '50m'
      memory: '256Mi'
    limits:
      cpu: '1000m'
      memory: '2Gi'