apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-deployment
  labels:
    app: studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studio
  template:
    metadata:
      labels:
        app: studio
    spec:
      containers:
      - name: studio
        image: {{ .Values.studio.image }}:{{ .Values.studio.tag }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4000
{{- if .Values.studio.resources  }}
        resources:
{{ toYaml .Values.studio.resources | indent 10 }}
{{- end }}