{{- if and .Values.studio.hpa .Values.studio.resources }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: studio-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: studio-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.studio.hpa.targetCpuUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.studio.hpa.targetMemory }}
{{- end }}
