apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-deployment
  labels:
    app: studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studio
  template:
    metadata:
      labels:
        app: studio
    spec:
      containers:
      - name: studio
        {{- with .Values.studio }}
        image: {{ .image }}:{{ .tag }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4000
        resources:
          requests:
            cpu: {{ .resources.requests.cpu }}
            memory: {{ .resources.requests.memory }}
          limits:
            cpu: {{ .resources.limits.cpu }}
            memory: {{ .resources.limits.memory }}
        {{- end }}