apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-worker-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: engine-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: engine-worker
    spec:
      serviceAccountName: provisioner-sa
      containers:
      - name: engine-worker
        {{- with .Values.engine.worker }}
        image: {{ .image }}:{{ .tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
          - name: CACHE_HOSTNAME
            value: redis-master
          - name: CACHE_READ_REPLICA_HOSTNAME
            value: redis-replicas
          - name: CACHE_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
          - name: CACHE_READ_REPLICA_PWD
            valueFrom:
               secretKeyRef:
                  name: redis-password
                  key: password
          - name: QUEUE_USERNAME
            valueFrom:
               secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
          - name: QUEUE_PASSWORD
            valueFrom:
               secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
          - name: QUEUE_HOST
            valueFrom:
               secretKeyRef:
                  name: rabbitmq-credentials
                  key: host
          - name: CLUSTER_DB_URI
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: clusterDBURI
          - name: CLUSTER_DB_USER
            value: "mongo-user"
          - name: CLUSTER_DB_PWD
            valueFrom:
               secretKeyRef:
                  name: mongodb-admin-password
                  key: password
          - name: MASTER_TOKEN
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: masterToken
          - name: ACCESS_TOKEN
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: accessToken
          - name: PASSPHRASE
            valueFrom:
               secretKeyRef:
                  name: cluster-secrets
                  key: passPhrase
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 3
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /health
            port: 4000
          failureThreshold: 30
          periodSeconds: 30
        resources:
            requests:
               cpu: {{ .resources.requests.cpu }}
               memory: {{ .resources.requests.memory }}
            limits:
               cpu: {{ .resources.limits.cpu }}
               memory: {{ .resources.limits.memory }}
        {{- end }}
