name: Build and Deploy

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apps/Chart.yaml'
      - 'base/Chart.yaml'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Charts
        uses: actions/checkout@v3
        with:
          ref: master
          path: charts
      -
        name: Checkout Pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Package Helm Charts
        run: |
          cd ./charts
          for chart_name in apps base
          do
            helm package --dependency-update ${chart-name}
            mkdir ${chart-name}-chart
            mv ${chart-name}-*.tgz ${chart-name}-chart/
            helm repo index ${chart-name}-chart --url https://cloud-agnost.github.io/charts/
            mv ${chart-name}-chart/* ../pages/
          done
      -
        name: Publish on Pages
        run: |
          cd ./pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "New release"
          git push
