name: Build and Deploy

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apps/Chart.yaml'
      - 'base/Chart.yaml'
      - 'README.md'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Charts
        uses: actions/checkout@v3
        with:
          ref: master
          path: charts
      -
        name: Checkout Pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Package Helm Charts
        run: |
          cd ./charts
          mkdir chart-files
          for chart_name in apps base
          do
            helm package --dependency-update ${chart_name}
            mv ${chart_name}-*.tgz chart-files
          done
          helm repo index chart-files --url https://cloud-agnost.github.io/charts/
          mv chart-files/* ../pages/
          cp README.md ../pages/
      -
        name: Publish on Pages
        run: |
          cd ./pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "New release"
          git push
