name: Build and Deploy

on:
  push:
    branches:
      - 'master'
    paths:
      - 'base/Chart.yaml'

env:
  DOCKER_REGISTRY: 'us.gcr.io'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Charts
        uses: actions/checkout@v3
        with:
          ref: master
          path: charts
      -
        name: Checkout Pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
      -
        name: Package Helm Charts
        run: |
          cd ./charts
          helm package base
          mkdir base-chart
          mv base-*.tgz base-chart/
          helm repo index base-chart --url https://cloud-agnost.github.io/charts/
          mv base-chart/* ../pages/
      -
        name: Publish on Pages
        run: |
          cd ./pages
          git config user.name ${{ secrets.REPO_ACCESS_USER }}
          git config user.email ${{ secrets.REPO_ACCESS_EMAIL }}
          git add .
          git commit -m "New release"
          git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/cloud-agnost/charts
